FROM node:22-alpine

RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm --filter api exec prisma generate

RUN pnpm --filter api build

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["pnpm", "start:prod"]